name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM
      run: wget https://apt.llvm.org/llvm.sh && sh llvm.sh 14
    - name: Build 
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run unit tests
      run: sh test.sh
